local vim = vim
local Plug = vim.fn["plug#"]

vim.call("plug#begin")

Plug("kyazdani42/nvim-tree.lua")
Plug("kyazdani42/nvim-web-devicons")
Plug("romgrk/barbar.nvim")
Plug("nvim-lualine/lualine.nvim")
Plug("nvim-treesitter/nvim-treesitter", { ["do"] = ":TSUpdate" })
Plug("neovim/nvim-lspconfig")
Plug("hrsh7th/cmp-buffer")
Plug("hrsh7th/cmp-path")
Plug("hrsh7th/cmp-cmdline")
Plug("hrsh7th/nvim-cmp")
Plug("hrsh7th/cmp-nvim-lsp")
Plug("hrsh7th/cmp-nvim-lsp-signature-help")
Plug("stevearc/conform.nvim")
Plug("catppuccin/nvim", { as = "catppuccin" })
Plug("ray-x/go.nvim")
Plug("ray-x/guihua.lua")
Plug("nvim-lua/plenary.nvim")
Plug("nvim-telescope/telescope.nvim")
Plug("akinsho/nvim-bufferline.lua")
Plug("akinsho/toggleterm.nvim")
Plug("kdheepak/lazygit.nvim")
Plug("MunifTanjim/nui.nvim")
Plug("crnvl96/lazydocker.nvim")
Plug("lewis6991/gitsigns.nvim")
Plug("folke/which-key.nvim")
Plug("folke/todo-comments.nvim")
Plug("lukas-reineke/indent-blankline.nvim")

vim.call("plug#end")

home = os.getenv("HOME")
package.path = home .. "/.config/nvim/?.lua;" .. package.path
vim.opt.rtp:prepend(vim.fn.stdpath("config") .. "/plugins")

vim.cmd("colorscheme catppuccin-frappe")

require("maps")
require("common")
-- dofile("theme.lua")
require("plugins.vimtree")
require("plugins.bufferline")
require("plugins.lua_line")
require("plugins.treesitter")
require("plugins.lsp")
require("plugins.cmp_config")
require("plugins.conform")
require("plugins.go")
require("plugins.telescope")
require("plugins.terminal")
require("plugins.lazydocker")
require("plugins.gitsigns")
require("plugins.whichkey")
require("plugins.todo_comments")
require("plugins.indent_blankline")
